name: Release Drafter Publisher

on:
  push:
    tags:
      - 'v*'

jobs:
    publish-release-draft:
        runs-on: ubuntu-latest
        steps:
          - name: Publish Release Drafter
            uses: release-drafter/action@v6
            with:
              disable-autolabeler: true
              name: ${{ github.ref_name }}
              tag: ${{ github.ref_name }}
              version: ${{ github.ref_name }}
              publish: true
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}