name: Release Drafter

on:
  push:
    branches:
      - main
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  invoke_release_drafter:
    uses: khanh-company-1/github-workflows/.github/workflows/release-drafter.yml@main